package edu.jooq.tables.records;

import edu.jooq.tables.Chats;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatsRecord extends UpdatableRecordImpl<ChatsRecord> implements Record4<Long, Integer, Integer, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHATS.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHATS.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CHATS.WAIT_TRACK</code>.
     */
    public void setWaitTrack(@Nullable Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>CHATS.WAIT_TRACK</code>.
     */
    @Nullable
    public Integer getWaitTrack() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>CHATS.WAIT_UNTRACK</code>.
     */
    public void setWaitUntrack(@Nullable Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>CHATS.WAIT_UNTRACK</code>.
     */
    @Nullable
    public Integer getWaitUntrack() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>CHATS.CREATED_AT</code>.
     */
    public void setCreatedAt(@NotNull OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>CHATS.CREATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, Integer, Integer, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<Long, Integer, Integer, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Chats.CHATS.CHAT_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return Chats.CHATS.WAIT_TRACK;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return Chats.CHATS.WAIT_UNTRACK;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field4() {
        return Chats.CHATS.CREATED_AT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getChatId();
    }

    @Override
    @Nullable
    public Integer component2() {
        return getWaitTrack();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getWaitUntrack();
    }

    @Override
    @NotNull
    public OffsetDateTime component4() {
        return getCreatedAt();
    }

    @Override
    @NotNull
    public Long value1() {
        return getChatId();
    }

    @Override
    @Nullable
    public Integer value2() {
        return getWaitTrack();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getWaitUntrack();
    }

    @Override
    @NotNull
    public OffsetDateTime value4() {
        return getCreatedAt();
    }

    @Override
    @NotNull
    public ChatsRecord value1(@NotNull Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord value2(@Nullable Integer value) {
        setWaitTrack(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord value3(@Nullable Integer value) {
        setWaitUntrack(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord value4(@NotNull OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord values(@NotNull Long value1, @Nullable Integer value2, @Nullable Integer value3, @NotNull OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    @ConstructorProperties({ "chatId", "waitTrack", "waitUntrack", "createdAt" })
    public ChatsRecord(@NotNull Long chatId, @Nullable Integer waitTrack, @Nullable Integer waitUntrack, @NotNull OffsetDateTime createdAt) {
        super(Chats.CHATS);

        setChatId(chatId);
        setWaitTrack(waitTrack);
        setWaitUntrack(waitUntrack);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(edu.jooq.tables.pojos.Chats value) {
        super(Chats.CHATS);

        if (value != null) {
            setChatId(value.getChatId());
            setWaitTrack(value.getWaitTrack());
            setWaitUntrack(value.getWaitUntrack());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
