app:
  database-access-type: jpa
  api:
    bot-base-url: http://localhost:8090
    github-base-url: https://api.github.com/
    stackoverflow-base-url: https://api.stackexchange.com/2.3/questions/
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
