package edu.jooq;

import edu.jooq.tables.ChatLinkConnection;
import edu.jooq.tables.Chats;
import edu.jooq.tables.Links;
import edu.jooq.tables.records.ChatLinkConnectionRecord;
import edu.jooq.tables.records.ChatsRecord;
import edu.jooq.tables.records.LinksRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatLinkConnectionRecord> ID = Internal.createUniqueKey(ChatLinkConnection.CHAT_LINK_CONNECTION, DSL.name("ID"), new TableField[] { ChatLinkConnection.CHAT_LINK_CONNECTION.CHAT_ID, ChatLinkConnection.CHAT_LINK_CONNECTION.LINK_ID }, true);
    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] { Chats.CHATS.CHAT_ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] { Links.LINKS.URL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkConnectionRecord, ChatsRecord> CONSTRAINT_B = Internal.createForeignKey(ChatLinkConnection.CHAT_LINK_CONNECTION, DSL.name("CONSTRAINT_B"), new TableField[] { ChatLinkConnection.CHAT_LINK_CONNECTION.CHAT_ID }, Keys.CONSTRAINT_3, new TableField[] { Chats.CHATS.CHAT_ID }, true);
    public static final ForeignKey<ChatLinkConnectionRecord, LinksRecord> CONSTRAINT_BF = Internal.createForeignKey(ChatLinkConnection.CHAT_LINK_CONNECTION, DSL.name("CONSTRAINT_BF"), new TableField[] { ChatLinkConnection.CHAT_LINK_CONNECTION.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
}
