package edu.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Chats implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long chatId;
    private Integer waitTrack;
    private Integer waitUntrack;
    private OffsetDateTime createdAt;

    public Chats() {}

    public Chats(Chats value) {
        this.chatId = value.chatId;
        this.waitTrack = value.waitTrack;
        this.waitUntrack = value.waitUntrack;
        this.createdAt = value.createdAt;
    }

    @ConstructorProperties({ "chatId", "waitTrack", "waitUntrack", "createdAt" })
    public Chats(
        @NotNull Long chatId,
        @Nullable Integer waitTrack,
        @Nullable Integer waitUntrack,
        @NotNull OffsetDateTime createdAt
    ) {
        this.chatId = chatId;
        this.waitTrack = waitTrack;
        this.waitUntrack = waitUntrack;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>CHATS.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>CHATS.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>CHATS.WAIT_TRACK</code>.
     */
    @Nullable
    public Integer getWaitTrack() {
        return this.waitTrack;
    }

    /**
     * Setter for <code>CHATS.WAIT_TRACK</code>.
     */
    public void setWaitTrack(@Nullable Integer waitTrack) {
        this.waitTrack = waitTrack;
    }

    /**
     * Getter for <code>CHATS.WAIT_UNTRACK</code>.
     */
    @Nullable
    public Integer getWaitUntrack() {
        return this.waitUntrack;
    }

    /**
     * Setter for <code>CHATS.WAIT_UNTRACK</code>.
     */
    public void setWaitUntrack(@Nullable Integer waitUntrack) {
        this.waitUntrack = waitUntrack;
    }

    /**
     * Getter for <code>CHATS.CREATED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>CHATS.CREATED_AT</code>.
     */
    public void setCreatedAt(@NotNull OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Chats other = (Chats) obj;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.waitTrack == null) {
            if (other.waitTrack != null)
                return false;
        }
        else if (!this.waitTrack.equals(other.waitTrack))
            return false;
        if (this.waitUntrack == null) {
            if (other.waitUntrack != null)
                return false;
        }
        else if (!this.waitUntrack.equals(other.waitUntrack))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.waitTrack == null) ? 0 : this.waitTrack.hashCode());
        result = prime * result + ((this.waitUntrack == null) ? 0 : this.waitUntrack.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chats (");

        sb.append(chatId);
        sb.append(", ").append(waitTrack);
        sb.append(", ").append(waitUntrack);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
